title: "I'm honeymon(JiHeon Kim)."
email: "ihoneymon@gmail.com"
description: "허니몬(honeymon.io)의 블로그 입니다."
author: honeymon
baseurl: ""
url: "http://honeymon.io"
timezone: "Asia/Seoul"
encoding: "UTF-8"
highlighter: rouge

# Social Profiles
twitter_username: ihoneymon
github_username: ihoneymon
facebook_username: "kim.jiheon"

# Build settings
markdown: kramdown

#kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# paginate
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
