title: "I'm honeymon(JiHeon Kim)."
email: "ihoneymon@gmail.com"
description: "허니몬(honeymon.io)의 블로그 입니다."
author: honeymon
baseurl: ""
url: "http://honeymon.io"
timezone: "Asia/Seoul"
encoding: "UTF-8"

# Social Profiles
twitter_username: ihoneymon
github_username: ihoneymon
facebook_username: "kim.jiheon"

# Build settings
markdown: kramdown
asciidoc:
  processor: asciidoctor
  ext: asciidoc, adoc, asc
  page_attribute_prefix: jekyll
  require_front_matter_header: true
  attributes:
    - source-highlighter=pygments
    - pygments-css=style
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-asciidoc
