= 개발자의 여행법
honeymon, ihoneymon@gmail.com
v0.0.1, 2019-05-17

[quote, 대한민국 철학자 허니몬]
____
인생은 기나긴 여정이다.
____

자신이 태어난 고향을 떠나지 않고 머무는 이가 있는가 하면 새로운 경험을 위해 어딘가로 떠나는 이도 있다. 내 첫 해외여행은 스쿠버다이빙을 위해 떠난 여행이었다. 필리핀 사방비치로 떠나는 첫 여행은 낯선 풍경에 색다른감을 맘껏 느낄 수 있었다. 휴양과 스쿠버다이빙을 위해 변화되어...

[NOTE]
====
쓸게 없다...!

여행을 다니면서 휴대폰 카메라로 담기에는 뭔가 부족한 그런 것이 있다.

DSLR을 살까? 괜찮은 똑딱이를 살까?
====

'집-회사-집'(에 가기 전에 사람들을 만나거나 운동을 하러 가고) 반복적인 패턴을 벗어나는 일탈행위를 즐길 수 있다. +
이는 **우아한형제들**이라는 회사에 들어오면서 좀 더 여유로워졌다고 느끼고 있다. 월요일 오후 1시에 출근하기에 굳이 일요일 오후에 힘들게 집으로 돌아갈 필요가 없기 때문에 일요일 저녁 여행지에서 여유롭게 보낸 후 월요일 아침에 집으로 돌아와 출근하면 된다.
내가 살고 있는 집이 영동고속도로가 가까이에 있는 서울 외곽에 위치한 덕도 있다. 서울남부나 서부의 경우 인구밀집지역을 관통하면서 겪게되는 교통체증을 겪을 일이 많지 않다.


== 국내
[quote, 월급쟁이개발자 허니몬]
____
기분이 내키면 떠나는 여행
____

=== 레트가 생기기 전
나의 애마 '레트(레드 트랙스의 줄인말)'가 함께하게 되면서 국내 여행의 폭이 넓어지기 시작했다. 

=== 레트가 생긴 후
보통 혼자 다니는 편이라 차 뒷칸에 '슈퍼 블랙죠'(내가 타는 검은 로드바이크 애칭)를 실어놓고 아침일찍 출발하여 현지에 도착해서 라이딩을 즐긴다. 수도권만 벗어나도 지방도로는 한적하고 운치있는 곳이 많은 편이라 라이딩을 즐기기 좋다. 전국 각지에 계신 라이더들이 올리는 코스 정보도 다운로드 받으면 길잃을 걱정도 없다. 크흡!

그렇게 돌아다닌 후에는 현지에서 맛있는 집을 찾아 나선다. 

[NOTE]
====
현지 특색이 잘 묻어나는 맛있는 음식을 먹을 수 있다는 것이 여행의 묘미 아니겠는가?
====

== 국외
[quote, 월급쟁이개발자 허니몬]
____
어쩌다가 기분이 내키면 떠나는 여행
____

=== 스쿠버다이빙 투어

나는 ``#월급쟁이개발자`` 다. 또한 나는 스쿠버 다이빙 강사기도 하다. +

스쿠버 다이빙을 하기 위해 0000으로 떠난 것이 첫 해외여행이었다. 스쿠버 다이빙 강사가 계획을 세우고 가이드를 하는 여행이기에 일반적인 패키지 여행과 크게 다르지 않다. 참가자 각자가 비행기 티켓을 끊고 장비를 챙겨서 출발시간에 맞춰 공항에 집결해서 이동하고 공항에 도착하면 현지 픽업서비스를 이용하여 목적지까지 이동하여 짐을 풀고 다이빙을 즐긴다. 돌아오는 날은 비행 전 충분한 수면휴식을 위해 현지 여행을 한다. 뭐, 가도그만 가지 않아도 그만인 시간이라 크게 신경쓰지는 않지만 한번은 간다.

늦은밤 도착하는 세부를 하늘에서 내려다본 모습은...
우리나라처럼 산을 깍아서 아파트를 만들거나 건물을 세우지는 않는다. 대체적으로 지형을 그대로 이용하는 편이다. 

개발자의 필수품, '노트북'은 반드시 챙긴다. 수중에서 촬영한 영상도 보고 백업도 받는다. 

내년부터는 조금 더 다양한 여행을 떠나보려 한다.

=== 배낭영행

=== 휴양

== 정리